### ISSUE TITLE
Is input for wild and interactive the same?

### ISSUE THREAD

**Issue by Henry-E** [DeepPavlov/convai#24]
Hi, 

I'm just checking that the input format for both forms of human evaluation will be the same; interactive and wild. By which I mean will they both be like the example provided in the wild API documentation:
`/start\nmy cats are very special to me.\ni'm a construction worker.\ni enjoy building houses.\ni have 5 cats.\nmy dad taught me everything i know.`
I'm also assuming that the inputs will be preprocessed / tokenized, unlike in the example? 

It's a little pedantic to point out but this line in the docs is slightly misleading `one line with “/start” text, and four lines afterwards with sentences describing profile.` Since it could be five, and even the example in `Advanced Topics` has five persona sentences.

**Comment by Henry-E** [comment]
Also I've been emailing asking for a token, since developing something that maintains dialogue history correctly, without having any example of how the dialogue takes place is pretty tough!

**Comment by emilydinan** [comment]
Hi @Henry-E, for the MTurk evaluations, please see the examples of `interactive.py` in each of the folders [here](https://github.com/facebookresearch/ParlAI/tree/master/projects/convai2/baselines). The personas will be "fed" to the model in the standard way they are fed in the Persona-Chat task (in the `text` field of an act, pre-pended with "your persona:" and separated by newlines). With the interactive script, text from humans is also fed to the model in the text field of the "act". We will lowercase the human text since the Persona-Chat task is lowercased, etc., as discussed.

**Comment by Henry-E** [comment]
Thanks so much for the help. It would also be great to get a little clarification on the evaluation stuff as well.
- does the new 5-gram blocking rule also apply to the mechanical Turk evaluation?
- are the "wild" evaluation results going to be used in determining the winners?

**Comment by madrugado** [comment]
@Henry-E Have you received the token? It seems to me that we have provided all the tokens being requested.

The starting message will contain persona, it should be 4 sentences, but I'll check if we have 5 sentence personas in the pool.

**Comment by madrugado** [comment]
The email address is correct. Please send me direct email to valentin@ipavlov.ai, sorry for inconvenience.

**Comment by thomwolf** [comment]
Hi @emilydinan and @madrugado,
There are two things I am not sure I understand with regards to the wild_evaluation (discussing here for everybody).
1. In the [wild eval documentation example](https://github.com/DeepPavlov/convai/blob/master/wild/advanced.md#method-getupdates) I see there are no `Your persona: ` prepended to the inputs but [Emily mentioned](https://github.com/DeepPavlov/convai/issues/24#issuecomment-427154722) that `Your persona: ` are pre-pended to the inputs.
It makes some difference for the model. Can you confirm the human annotation persona input format?
2. Do we need to supply several type of scripts for human annotation? You are referring to the `interactive.py` scripts in the [baselines repo](https://github.com/facebookresearch/ParlAI/tree/master/projects/convai2/baselines) which are quite different from the `convai_bot.py` and `convai_world.py` linked in the [ParlAI integration of ConvAI](https://github.com/facebookresearch/ParlAI/tree/master/projects/convai) referenced in the [wild readme file](https://github.com/DeepPavlov/convai/tree/master/wild). We have based our human evaluation scripts on the later (i.e. handling server communication and adding `Your persona: ` to the input). Is this the way to go or should we supply interactive scripts that looks more like the `interactive.py` scripts in the [baselines repo](https://github.com/facebookresearch/ParlAI/tree/master/projects/convai2/baselines) (fine also for us).

**Comment by jaseweston** [comment]
The MTurk evaluation follows the *interactive* scripts that we (ParlAI
team) linked to, and is a standard interface into ParlAI, which ParlAI
MTurk uses.

The wild eval is being handled by our Moscow Institute of Physics and
Technology colleagues (they provided the wild readme file), and we have
asked them to make it as close as possible to the same interface, but
apparently is slightly different.  The eval should handle data in the same
way as training, which used "Your persona: " right? So that sounds like
there is a bug in their wild eval setup, and we need to get that fixed with
them (CCed).

**Comment by Henry-E** [comment]
It would be pretty helpful if the personas in wild eval could begin with "your persona:".

**Comment by madrugado** [comment]
We have done the changes in code, so now the input for your bot using ConvAI integration is compliant with PersonaChat dataset.
