### ISSUE TITLE
Explanation on the data collected during the human evaluation round

### ISSUE THREAD

**Issue by calee88** [DeepPavlov/convai#7]
I think I understand most of it. However, turn scores are confusing to me. According to data/Dataset_Analysis.ipynb, it looks like 0 means bad, 1 means neutral, and 2 means good. Humans got 0 by bots, and that's why humans are worse than bots.

Am I understanding correctly?

**Comment by DeepPavlov** [comment]
Bots can't score humans. In human vs bot dialogues only human evaluates a bot and scores for human's turns just filled with zeroes.

Is this answers your question?

**Comment by calee88** [comment]
Yes, but partly. I know that scores for human's turns are just filled with zeroes. But isn't zero mean bad score for bots? I am thinking that it would be better if those scores are filled with ones, because it means neutral. So that, humans and bots can be compared fairly.

**Comment by varvara-l** [comment]
Hi @calee88 , 
in our data there are three utterance-level scores: "0" means no score, "1" - "bad", "2" - "good". There is no "neutral" score. Bots can't rate human performance, so all human utterances are rated with "0". Likewise, if a bot utterance got no score from a human, in the dataset it has a score "0".
This representation is probably a bit of a nuisance, we'll try to fix it in the next versions of the dataset.

That created confusion in the first version of Dataset_Analysis.ipynb file - it looked like humans are worse than bots because they have much more zeros. We've now re-computed the distribution of human and bot scores where we discarded all zeros. Please see the new version of the file, section 2.2 "Utterance-level quality".

**Comment by calee88** [comment]
@varvara-l Great. Now it looks clear to me. Thank you.
